import type { Article } from '../types/article.types'

const CATEGORY = {
  politics: { _id: 'c2', name: 'রাজনীতি' },
  world: { _id: 'c4', name: 'বিশ্ব' },
  entertainment: { _id: 'c8', name: 'বিনোদন' },
  national: { _id: 'c1', name: 'জাতীয়' },
  sports: { _id: 'c5', name: 'খেলা' },
  business: { _id: 'c7', name: 'বাণিজ্য' },
  education: { _id: 'c6', name: 'শিক্ষা' },
  country: { _id: 'c3', name: 'সারাদেশ' },
}

function hoursAgo(h: number) {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString()
}

function makeThumbnail(url: string) {
  return { url, public_id: `mock/${url.split('/').pop()}` }
}

export const MOCK_ARTICLES: Article[] = [
  {
    _id: 'a1',
    title: 'বগুড়ায় যুবদলের ২ উপজেলা, ৩ পৌর কমিটি বিলুপ্ত',
    slug: 'bogura-jubodol-committee-dissolved',
    content:
      'বগুড়ায় সাংগঠনিকভাবে গতিশীল করার লক্ষ্যে যুবদলের ৫টি উপজেলা ও পৌর কমিটি বিলুপ্ত করা হয়েছে। শুক্রবার (৭ আগস্ট) দুপুরে বগুড়া জেলা যুবদলের সভাপতি জাহাঙ্গীর আলম ও সাধারণ সম্পাদক আবু হাসান স্বাক্ষরিত এক বিজ্ঞপ্তিতে এই কমিটি বিলুপ্তের ঘোষণা করা হয়।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.politics,
    tags: ['রাজনীতি', 'বগুড়া'],
    author: { _id: 'u1', fullName: 'প্রভাতবার্তা প্রতিবেদক' },
    shareCount: 12,
    status: 'published',
    isPremium: false,
    views: 8,
    publishedAt: hoursAgo(19 * 24),
    createdAt: hoursAgo(19 * 24),
    updatedAt: hoursAgo(19 * 24),
  },
  {
    _id: 'a2',
    title: 'বিশ্বকাপ থেকে ছিটকে গেল যে দুই দেশ',
    slug: 'world-cup-two-teams-eliminated',
    content: 'চূড়ান্তপর্বের বাছাইয়ে হেরে বিশ্বকাপের স্বপ্ন শেষ হলো দুটি দলের। ফুটবল বিশ্বকাপ বাছাইপর্বের শেষ ম্যাচে হারের ফলে দুটি দল বিশ্বকাপে জায়গা করে নিতে ব্যর্থ হয়েছে।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.sports,
    tags: ['খেলা', 'বিশ্বকাপ'],
    author: { _id: 'u2', fullName: 'স্পোর্টস ডেস্ক' },
    shareCount: 87,
    status: 'published',
    isPremium: false,
    views: 412,
    publishedAt: hoursAgo(67 * 24),
    createdAt: hoursAgo(67 * 24),
    updatedAt: hoursAgo(67 * 24),
  },
  {
    _id: 'a3',
    title: 'নতুন সিনেমা মুক্তি পেল',
    slug: 'new-movie-released',
    content: 'দর্শকদের জন্য মুক্তি পেল বহুল প্রতীক্ষিত নতুন চলচ্চিত্রটি। প্রথম দিনেই দর্শকদের ব্যাপক সাড়া পাওয়া গেছে হলগুলোতে।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.entertainment,
    tags: ['বিনোদন', 'চলচ্চিত্র'],
    author: { _id: 'u3', fullName: 'বিনোদন প্রতিবেদক' },
    shareCount: 45,
    status: 'published',
    isPremium: false,
    views: 231,
    publishedAt: hoursAgo(115 * 24),
    createdAt: hoursAgo(115 * 24),
    updatedAt: hoursAgo(115 * 24),
  },
  {
    _id: 'a4',
    title: 'বাংলাদেশে তাপমাত্রা বেড়েছে',
    slug: 'temperature-rising-in-bangladesh',
    content: 'আবহাওয়া অধিদপ্তরের পূর্বাভাসে সপ্তাহজুড়ে তাপমাত্রা বৃদ্ধির শঙ্কা প্রকাশ করা হয়েছে। রাজধানীসহ দেশের বিভিন্ন অঞ্চলে তাপপ্রবাহ অব্যাহত থাকতে পারে।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1504370805625-d32c54b16100?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.national,
    tags: ['জাতীয়', 'আবহাওয়া'],
    author: { _id: 'u1', fullName: 'প্রভাতবার্তা প্রতিবেদক' },
    shareCount: 20,
    status: 'published',
    isPremium: false,
    views: 156,
    publishedAt: hoursAgo(115 * 24),
    createdAt: hoursAgo(115 * 24),
    updatedAt: hoursAgo(115 * 24),
  },
  {
    _id: 'a5',
    title: 'কক্সবাজারে পর্যটকের ভিড়',
    slug: 'coxs-bazar-tourist-crowd',
    content: 'ছুটির দিনে কক্সবাজার সমুদ্র সৈকতে পর্যটকদের ভিড় বেড়েছে। হোটেলগুলোতে বুকিং পূর্ণ, বাড়তি নিরাপত্তা ব্যবস্থা নিয়েছে প্রশাসন।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.national,
    tags: ['জাতীয়', 'পর্যটন'],
    author: { _id: 'u1', fullName: 'প্রভাতবার্তা প্রতিবেদক' },
    shareCount: 33,
    status: 'published',
    isPremium: false,
    views: 98,
    publishedAt: hoursAgo(115 * 24),
    createdAt: hoursAgo(115 * 24),
    updatedAt: hoursAgo(115 * 24),
  },
  {
    _id: 'a6',
    title: 'পদ্মা সেতুতে ঈদে বাড়ছে যান চলাচল',
    slug: 'padma-bridge-eid-traffic',
    content: 'ঈদকে সামনে রেখে পদ্মা সেতুতে যানবাহনের চাপ বেড়েছে। টোল প্লাজায় দীর্ঘ সারি লক্ষ্য করা গেছে, ভোগান্তি এড়াতে বাড়তি লেন চালু করা হয়েছে।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.country,
    tags: ['সারাদেশ', 'পদ্মা সেতু'],
    author: { _id: 'u4', fullName: 'জেলা প্রতিনিধি' },
    shareCount: 61,
    status: 'published',
    isPremium: false,
    views: 302,
    publishedAt: hoursAgo(126 * 24),
    createdAt: hoursAgo(126 * 24),
    updatedAt: hoursAgo(126 * 24),
  },
  {
    _id: 'a7',
    title: 'নতুন স্মার্টফোন বাজারে',
    slug: 'new-smartphone-launch',
    content: 'একটি জনপ্রিয় ব্র্যান্ড তাদের নতুন স্মার্টফোন উন্মোচন করেছে, যেখানে উন্নত ক্যামেরা ও ব্যাটারি সুবিধা রয়েছে। দাম নিয়ে ইতিমধ্যে আলোচনা শুরু হয়েছে ক্রেতামহলে।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.business,
    tags: ['বাণিজ্য', 'প্রযুক্তি'],
    author: { _id: 'u5', fullName: 'বাণিজ্য প্রতিবেদক' },
    shareCount: 18,
    status: 'published',
    isPremium: false,
    views: 176,
    publishedAt: hoursAgo(115 * 24),
    createdAt: hoursAgo(115 * 24),
    updatedAt: hoursAgo(115 * 24),
  },
  {
    _id: 'a8',
    title: 'ঢাকায় হঠাৎ ভারী বৃষ্টিতে জলাবদ্ধতা',
    slug: 'dhaka-sudden-rain-waterlogging',
    content: 'আজ বিকেলে ঢাকার বিভিন্ন এলাকায় হঠাৎ ভারী বৃষ্টি শুরু হয়। এতে শহরের রাস্তায় পানি জমে যায় এবং যান চলাচলে ব্যাপক বিঘ্ন ঘটে।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.country,
    tags: ['সারাদেশ', 'ঢাকা'],
    author: { _id: 'u4', fullName: 'জেলা প্রতিনিধি' },
    shareCount: 40,
    status: 'published',
    isPremium: false,
    views: 264,
    publishedAt: hoursAgo(115 * 24),
    createdAt: hoursAgo(115 * 24),
    updatedAt: hoursAgo(115 * 24),
  },
  {
    _id: 'a9',
    title: 'ঢাকা বিশ্ববিদ্যালয়ে ভর্তি পরীক্ষা শুরু',
    slug: 'du-admission-test-begins',
    content: 'ঢাকা বিশ্ববিদ্যালয়ে আজ থেকে ভর্তি পরীক্ষা শুরু হয়েছে। দেশের বিভিন্ন স্থান থেকে শিক্ষার্থীরা অংশগ্রহণ করছে এই পরীক্ষায়।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.education,
    tags: ['শিক্ষা', 'ঢাবি'],
    author: { _id: 'u6', fullName: 'শিক্ষা প্রতিবেদক' },
    shareCount: 25,
    status: 'published',
    isPremium: false,
    views: 189,
    publishedAt: hoursAgo(126 * 24),
    createdAt: hoursAgo(126 * 24),
    updatedAt: hoursAgo(126 * 24),
  },
  {
    _id: 'a10',
    title: 'শেয়ারবাজারে সূচকের উত্থান',
    slug: 'stock-market-index-rise',
    content: 'আজ শেয়ারবাজারে সূচকের বড় ধরনের উত্থান হয়েছে। বিনিয়োগকারীদের মধ্যে আশাবাদ দেখা যাচ্ছে, লেনদেনের পরিমাণও বেড়েছে।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.business,
    tags: ['বাণিজ্য', 'শেয়ারবাজার'],
    author: { _id: 'u5', fullName: 'বাণিজ্য প্রতিবেদক' },
    shareCount: 15,
    status: 'published',
    isPremium: false,
    views: 143,
    publishedAt: hoursAgo(126 * 24),
    createdAt: hoursAgo(126 * 24),
    updatedAt: hoursAgo(126 * 24),
  },
  {
    _id: 'a11',
    title: 'নির্বাচন কমিশনে সংলাপ আহ্বান করলেন প্রধান উপদেষ্টা',
    slug: 'ec-dialogue-chief-adviser',
    content: 'আগামী জাতীয় নির্বাচনকে সামনে রেখে সব রাজনৈতিক দলের সাথে সংলাপ আহ্বান করেছেন প্রধান উপদেষ্টা। তিনি বলেন, একটি অংশগ্রহণমূলক নির্বাচনই জাতির চাওয়া।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.politics,
    tags: ['রাজনীতি', 'নির্বাচন'],
    author: { _id: 'u1', fullName: 'প্রভাতবার্তা প্রতিবেদক' },
    shareCount: 92,
    status: 'published',
    isPremium: false,
    views: 522,
    publishedAt: hoursAgo(132 * 24),
    createdAt: hoursAgo(132 * 24),
    updatedAt: hoursAgo(132 * 24),
  },
  {
    _id: 'a12',
    title: 'রেমিট্যান্স প্রবাহে নতুন রেকর্ড, এপ্রিলে এলো ২.৫ বিলিয়ন ডলার',
    slug: 'remittance-new-record-april',
    content: 'চলতি অর্থবছরের এপ্রিল মাসে প্রবাসী আয়ে নতুন রেকর্ড গড়েছে বাংলাদেশ। কেন্দ্রীয় ব্যাংকের তথ্য অনুযায়ী এই প্রবৃদ্ধি অব্যাহত থাকবে বলে আশা প্রকাশ করেছেন বিশেষজ্ঞরা।',
    thumbnail: makeThumbnail('https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80'),
    mediaFiles: [],
    category: CATEGORY.business,
    tags: ['বাণিজ্য', 'রেমিট্যান্স'],
    author: { _id: 'u5', fullName: 'বাণিজ্য প্রতিবেদক' },
    shareCount: 8,
    status: 'published',
    isPremium: false,
    views: 67,
    publishedAt: hoursAgo(1),
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
]

export const MOCK_ARTICLE_DETAIL: Article = MOCK_ARTICLES[0]
